/// Flutter icons Otaghak
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Otaghak
///      fonts:
///       - asset: fonts/Otaghak.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'Otaghak';

  static const IconData favorite = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData explore = const IconData(0xe803, fontFamily: _kFontFam);
}
